// <auto-generated />
using System;
using LibrarySystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystem.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("BookModelGenreModel", b =>
                {
                    b.Property<Guid>("BooksId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("TEXT");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookModelGenreModel");
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.GenreModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.LibraryCardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("LibraryCards");
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.LibraryItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearPublished")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("LibraryItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.MemberModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.PublisherModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.BookModel", b =>
                {
                    b.HasBaseType("LibrarySystem.Infrastructure.Models.LibraryItemModel");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.MagazineModel", b =>
                {
                    b.HasBaseType("LibrarySystem.Infrastructure.Models.LibraryItemModel");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable("Magazines", (string)null);
                });

            modelBuilder.Entity("BookModelGenreModel", b =>
                {
                    b.HasOne("LibrarySystem.Infrastructure.Models.BookModel", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystem.Infrastructure.Models.GenreModel", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.LibraryCardModel", b =>
                {
                    b.HasOne("LibrarySystem.Infrastructure.Models.MemberModel", "Member")
                        .WithOne("LibraryCard")
                        .HasForeignKey("LibrarySystem.Infrastructure.Models.LibraryCardModel", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.LibraryItemModel", b =>
                {
                    b.HasOne("LibrarySystem.Infrastructure.Models.PublisherModel", "Publisher")
                        .WithMany("PublishedItems")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.BookModel", b =>
                {
                    b.HasOne("LibrarySystem.Infrastructure.Models.LibraryItemModel", null)
                        .WithOne()
                        .HasForeignKey("LibrarySystem.Infrastructure.Models.BookModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.MagazineModel", b =>
                {
                    b.HasOne("LibrarySystem.Infrastructure.Models.LibraryItemModel", null)
                        .WithOne()
                        .HasForeignKey("LibrarySystem.Infrastructure.Models.MagazineModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.MemberModel", b =>
                {
                    b.Navigation("LibraryCard")
                        .IsRequired();
                });

            modelBuilder.Entity("LibrarySystem.Infrastructure.Models.PublisherModel", b =>
                {
                    b.Navigation("PublishedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
